## 푸시기 전에 .. 

```
#### 기말고사 규칙:
- 기말고사는 오픈북 형태로서 수업시간 자료와 외부 자료를 모두 조회, 참고 가능합니다. 
- 인터넷 검색도 가능하지만 타인과의 정보교환은 엄격히 금합니다. 적발시 바로 부정행위로 조치합니다. 
- 수험 시간은 시작 이후 1시간 20분까지입니다. 
- 점수는 작성하신 프로그램중에 가장 난이도가 높은 프로그램으로 반영됩니다. 그러므로 가장 난이도가 높은 프로그램 하나만 정확히 작성하셔도 만점입니다. 
- 어려운 문제에 매달리다 실패하는 위험을 줄이기 위해 자신있는 문제를 먼저 푸시고 도전할만한 문제를 푸시는걸 추천드립니다. 
- 수업시간에 알려드린 방식과 다르거나 지나치게 유사한 답안이 존재할 경우  본인이 푸신걸 확인하기 위한 절차를 요청할 수 있습니다. 이때 설명을 못하시면 부정시험으로 간주합니다. 
```

다음은 여러분들의 편의를 위한 시험에 사용되는 라이브러리 import 코드입니다.

In [ ]:
import numpy as np 
import matplotlib.pyplot as plt 
import math
import pandas as pd



# 2021 학년도 2학기 컴퓨터실습2 기말고사 (실습2과정) [2분반]

<br>


---
<Br><Br><Br>

#### 문제 1. 다음 x,y 2개의 의 값을 갖는 Point 클래스에서 두 값을 서로 바꿔주는 swap() 메소드를 만드세요 [60점]

사용예:
```
p = Point(3,4)
p.swap()
print(p)

-> 4,3
```

```

In [ ]:
# 클래스 Point 정의
class Point:
  def __init__(self,x,y):
    self.x = x
    self.y = y 
  
  # 메소드 swap 를 작성하세요
 

  #문자열 변환 메소드
  def __str__(self):
    return str(self.x) + "," + str(self.y)


# 사용예 
p = Point(3,4)
p.swap()
print(p)


---
<Br><Br><Br>

#### 문제 2. 다음과 같은 pandas data frame 을 만들고 출력해보세요 [70점]

```
       type  posx  posy  color
0  triangle    43    55    red
1    square     5    13   blue
2    circle    32    41  green
```


In [ ]:
# 문제 2의 형태의 데이터 프레임을 생성하고 출력하세요



---
<Br><Br><Br>

#### 문제 3. 다음과 형태의 7x7 ndarray 배열을 수동 입력이나 반복문을 사용하지 안고 만드세요 [80점]
```
[[0 1 0 1 0 1 0]
 [1 2 2 2 2 2 1]
 [0 2 2 2 2 2 0]
 [1 2 2 2 2 2 1]
 [0 2 2 2 2 2 0]
 [1 2 2 2 2 2 1]
 [0 1 0 1 0 1 0]]
```




In [ ]:
# 문제의 형태가 되도록 numpy 배열 a 를 만드세요


# 출력
print(a)





---


<Br><Br><Br>

#### 문제 4. matplotlib의 plot 과 math.sin 함수를 을 사용해서 다음 형태를 그려보세요 [90점]

<img src = 'http://drive.google.com/uc?export=view&id=1PiTc8npDRJ-80nLZPS2lONm-J1COCHq3'>

In [ ]:
# 문제 4번의 코드를 여기에 작성하세요


---
<Br><Br><Br>

#### 문제 5. 다음 형태의 딕셔너리에서 모든 값들을 배열로 리턴하는 함수 dicList(dic) 을 만드세요  [100점]

dic 형태:
```
 a : 1
 b : 2
 c :
    c1 : 3
    c2 :
       c21 : 21
       c22 : 27
 d :
    d1 : 4
    d2 : 5
```

출력:
```
print( dicList(nest) )
-:
[1, 2, 3, 21, 27, 4, 5]


In [ ]:
# 데이터 ( dic 의 구조를 바꾸면서 테스트 해보세요 )
nest = { "a":1, 
        "b":2,
        "c":{
          "c1":3,
          "c2":{
            "c21":21,
            "c22":27
          }        
        },
        "d":{
            "d1":4,
            "d2":5
        }

      }

def dicList(dic) :  
  l = []
  # 재귀함수 dicList 의 코드를 여기에 작성하세요  
   




   
  # 결과 배열 리턴
  return l 

print( dicList(nest) )



### 제출 시 참고 : 
- 과제 제출은 작성하신 colab을 [파일 > 다운로드 > ipynb] 메뉴를 통해 파일로 다운 받으신 후에 사이버캠퍼스 [기말고사 제출] 이라는 과제에 업로드하셔야 합니다.
- 웹브라우저(크롬, ie, 엣지 파폭)의 메뉴가 아닌 colab 에 있는 다운로드를 사용하셔야 정상적으로 ipynb 로 다운로드 됩니다. 
