## 푸시기 전에 .. 

```
#### 기말고사 규칙:
- 기말고사는 오픈북 형태로서 수업시간 자료와 외부 자료를 모두 조회, 참고 가능합니다. 
- 인터넷 검색도 가능하지만 타인과의 정보교환은 엄격히 금합니다. 적발시 바로 부정행위로 조치합니다. 
- 수험 시간은 시작 이후 1시간 50분까지입니다. 
- 점수는 작성하신 프로그램중에 가장 난이도가 높은 프로그램으로 반영됩니다. 그러므로 가장 난이도가 높은 프로그램 하나만 정확히 작성하셔도 만점입니다. 
- 어려운 문제에 매달리다 실패하는 위험을 줄이기 위해 자신있는 문제를 먼저 푸시고 도전할만한 문제를 푸시는걸 추천드립니다. 
- 수업시간에 알려드린 방식과 다르거나 지나치게 유사한 답안이 존재할 경우  본인이 푸신걸 확인하기 위한 절차를 요청할 수 있습니다. 이때 설명을 못하시면 부정시험으로 간주합니다. 
```

다음은 여러분들의 편의를 위한 시험에 사용되는 라이브러리 import 코드입니다.

In [ ]:
import numpy as np 
import matplotlib.pyplot as plt 
import math
import pandas as pd



# 2021 학년도 컴퓨터실습2 기말고사 (실습2과정)
<br>


---
<Br><Br><Br>

#### 문제 1. 다음 x,y 두개의 값을 갖는 Point 클래스에 x,y 값만큼 이동시키는 move 메소드를 작성하세요 [60점]

사용예:
```
p = Point(3,4)
p.move(3,-1)
print(p)
-> 
6,3
```




In [2]:
# 클래스 Point 정의
class Point:
  def __init__(self,x,y): #생성자
    self.x = x
    self.y = y 
  
  def __str__(self): #문자열 변환 메소드
    return str(self.x) + "," + str(self.y)

  # 메소드 move 를 작성하세요




 


# 사용예 
p = Point(3,4)
p.move(3,-1)
print(p)


6,3


---
<br><br><br>

#### 문제 2. 다음 ndarray 를 보기와 같이 바꾸세요 [70점]

보기:
```
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

->

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
```

In [ ]:
# 클래스 정의 코드
arr = np.zeros(25).reshape(5,5) % 2

#위의 numpy 배열을 보기와 같이 바꿔보세요


# 출력
print(arr)



---


<Br><Br><Br>

#### 문제 3. 다음 pandas 에서 읽어들인 데이터중에 SP 값이 7 이상인 경우에 대한 Slag 값을 그래프로 표시해보세요 [80점]
 
다음 

In [ ]:
# data 읽어들이기
df = pd.read_csv( 'https://archive.ics.uci.edu/ml/machine-learning-databases/concrete/slump/slump_test.data' ) 
df

# 문제의 코드를 작성하세요


---
<Br><Br><Br>

#### 문제 4. matplotlib 의 막대 차트 bar 를 사용해 다음과 형태를 그려보세요 [90점]
( 예시의 bar 의 갯수는 100개입니다. )

<img src = 'http://drive.google.com/uc?export=view&id=1v6n8A59-dyutqQoqTTKTLH9QlouqdNJo'>




In [ ]:
# 문제 4번의 형태가 되도록 데이터를 생성하고 막대그래프를 만들어보세요


---
<Br><Br><Br>

#### 문제 5. 다음 형태의 딕셔너리에서 특정값의 경로를 찾는 searchPath 함수를 작성하세요  [100점]



예: 

nest 
```
 a : 1
 b : 2
 c :
    c1 : 3
    c2 :
       c21 : 21
       c22 : 27
 d :
    d1 : 4
```

사용 예:
```
print( searchPath(nest,21) )
->
(['c', 'c2', 'c21'])
```

(단 값이 없을 경우 빈 배열이 리턴되도록 합니다. )

In [ ]:
# 데이터 ( 최대값의 위치를 바꿔서 테스트 해보세요 )
nest = { "a":1, 
        "b":2,
        "c":{
          "c1":3,
          "c2":{
            "c21":21,
            "c22":27
          }        
        },
        "d":{
            "d1":4,
            "d2":5
        }

      }

def searchPath(dic, v) :
  path = [] 
  # 재귀함수 searchPath 의 코드를 여기에 작성하세요
  

  # 최종적으로 path를 리턴합니다. 
  return path



# 테스트 코드 ( 찾는 값을 바꿔서 테스트해보세요 )
print( searchPath(nest, 21) )


### 제출 시 참고 : 
- 과제 제출은 작성하신 colab을 [파일 > 다운로드 > ipynb] 메뉴를 통해 파일로 다운 받으신 후에 사이버캠퍼스 [기말고사 제출] 이라는 과제에 업로드하셔야 합니다.
- 웹브라우저(크롬, ie, 엣지 파폭)의 메뉴가 아닌 colab 에 있는 다운로드를 사용하셔야 정상적으로 ipynb 로 다운로드 됩니다. 
