## 푸시기 전에 .. 

```
#### 기말고사 규칙:
- 기말고사는 오픈북 형태로서 수업시간 자료와 외부 자료를 모두 조회, 참고 가능합니다. 
- 인터넷 검색도 가능하지만 타인과의 정보교환은 엄격히 금합니다. 적발시 바로 부정행위로 조치합니다. 
- 수험 시간은 시작 이후 1시간 20분까지입니다. 
- 점수는 작성하신 프로그램중에 가장 난이도가 높은 프로그램으로 반영됩니다. 그러므로 가장 난이도가 높은 프로그램 하나만 정확히 작성하셔도 만점입니다. 
- 어려운 문제에 매달리다 실패하는 위험을 줄이기 위해 자신있는 문제를 먼저 푸시고 도전할만한 문제를 푸시는걸 추천드립니다. 
- 수업시간에 알려드린 방식과 다르거나 지나치게 유사한 답안이 존재할 경우  본인이 푸신걸 확인하기 위한 절차를 요청할 수 있습니다. 이때 설명을 못하시면 부정시험으로 간주합니다. 
```

다음은 여러분들의 편의를 위한 시험에 사용되는 라이브러리 import 코드입니다.

In [19]:
import numpy as np 
import matplotlib.pyplot as plt 
import math
import pandas as pd



# 2021 학년도 컴퓨터실습2 기말고사 (실습2과정)
<br>


---
<br><br><br>

#### 문제 1. 다음은 학생의 정보를 저장하는 클래스입니다. 다음과 형태로 출력이 가능하도록 info 메소드를 작성하세요 [60점]
```
stu1 = Student("곽주현", "970038") 
print( stu1.info() ) 
->
studnent name:곽주현 student no:970038

```

In [ ]:
# 클래스 정의 코드
class Student:  
  def __init__(self, name, stuno):
    self.name = name
    self.stuno = stuno 

# 메소드 info 를 여기에 작성하세요
  def info(self):
    return  "studnent name:" + self.name + " student no:" + self.stuno


# 클래스 사용코드
stu1 = Student("곽주현", "970038") 
print( stu1.info() ) 

---
<Br><Br><Br>

#### 문제 2. 다음과 형태로 ndarray 배열을 만드세요 [70점]
```
[[0 1 2 0 1]
 [2 0 1 2 0]
 [1 2 0 1 2]
 [0 1 2 0 1]
 [2 0 1 2 0]]
```




In [17]:
# 문제의 형태가 되도록 배열 a 를 만드세요
a = np.arange(25) % 3
a = a.reshape(-1,5) 

# 출력
print(a)



[[0 1 2 0 1]
 [2 0 1 2 0]
 [1 2 0 1 2]
 [0 1 2 0 1]
 [2 0 1 2 0]]


---
<Br><Br><Br>

#### 문제 3. 다음 pandas 데이터 에서 ash 를 x 축, Water 를 y축으로 화면에 점으로 표시해 plot 으로 출력해보세요 [80점]




In [ ]:
# pandas 데이터 불러오기
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/concrete/slump/slump_test.data')
df

# plot 출력을 작성하세요
x = df['Fly ash'].values
y = df['Water'].values

plt.plot(x,y,'.')



---


<Br><Br><Br>

#### 문제 4. matplotlib의 plot 을 사용해서 다음 형태를 그려보세요 [90점]

<img src = 'http://drive.google.com/uc?export=view&id=1Qoqw_yLV9TArxqPmZO_6aF1a_veVpN3S'>

In [ ]:
# 문제의 코드를 여기에 작성하세요
import math
n, theta = 40, []  

for i in range(n + 1): 
  theta += [ math.pi * 2 / n * i ]


x,y = [],[]
for th in theta:
  x += [  math.sin(th), 0]
  y += [  math.cos(th), 0]


plt.xlim( -1.6, 1.6)
plt.ylim( -1, 1 )
plt.plot(x,y, '-o')


---
<Br><Br><Br>

#### 문제 5. 다음 형태의 딕셔너리에서 최대값까지의 경로의 키값과 배열과 최대값을 같이 리턴하는 재귀함수 maxPath를 작성하세요 [100점]

dic 형태:
```
 a : 1
 b : 2
 c :
    c1 : 3
    c2 :
       c21 : 21
       c22 : 27
 d :
    d1 : 4
```

출력:
```
print( maxPath(nest) )
-:
(['c', 'c2', 'c22'], 27)


In [ ]:
# 데이터 ( 최대값의 위치를 바꿔서 테스트 해보세요 )
nest = { "a":1, 
        "b":2,
        "c":{
          "c1":3,
          "c2":{
            "c21":21,
            "c22":27
          }        
        },
        "d":{
            "d1":4,
            "d2":5
        }

      }

def maxPath(dic) :
  path,max  = [],0
  # 재귀함수 maxPath 의 코드를 여기에 작성하세요
  
  for k in dic:
    if type( dic[k] ) == dict : 
      cpath,cmax = maxPath( dic[k] ) # 하위 함수로부터 path 와 max 값을 받아서
      if cmax > max :    # 방금 받은 자식의 max 값이 기존보다 더 크면
        path = [k] + cpath    # 자식의 path 에 자신의 key 값을 더해서 새로운 path 로 교체 
        max = cmax
    else :
      if dic[k] > max:
        path = [k]
        max = dic[k]

  # 2개의 값을 동시 리턴 
  return path,max # 스스로도 path 와 max 값을 리턴함

print( maxPath(nest) )


### 제출 시 참고 : 
- 과제 제출은 작성하신 colab을 [파일 > 다운로드 > ipynb] 메뉴를 통해 파일로 다운 받으신 후에 사이버캠퍼스 [기말고사 제출] 이라는 과제에 업로드하셔야 합니다.
- 웹브라우저(크롬, ie, 엣지 파폭)의 메뉴가 아닌 colab 에 있는 다운로드를 사용하셔야 정상적으로 ipynb 로 다운로드 됩니다. 
